### PR TITLE
katex: Ensure MathML actually displays

### PR DESCRIPTION
**Pull request by auscompgeek**

### CODE REVIEW

**Comment by fred-wang** [comment]
Thanks. Do you have a test case or explanation ? 

(that does not seem necessary on https://khan.github.io/KaTeX/ )

**Comment by auscompgeek** [comment]
I use a website, specifically a LMS <https://edstem.org>, that has this rule:
```css
.katex .katex-mathml {
    display: none;
}
```

Maybe we shouldn't have a `!important` on this though…

**Comment by fred-wang** [comment]
OK, I think it makes sense to have this rule then since the users of the add-on wants to see the MathML. Does this work without the !important ?

**Comment by auscompgeek** [comment]
Oops, sorry for leaving this thread dangling.

It seems to work without the !important, yes.

**Comment by fred-wang** [comment]
@auscompgeek Can you please update your PR to not use the "!important" then? Thanks!

**Comment by auscompgeek** [comment]
Sure. Do you think there should also be a comment explaining that this doesn't acutally override a rule provided by KaTeX's CSS, but rather some websites' own CSS rules?

**Comment by fred-wang** [comment]
Yes, I guess a comment could be useful

**Comment by fred-wang** [comment]
@auscompgeek Sorry, I missed your patch. Merging now. Thanks!

**Pull request merged**
